"""Qt-free proactive monitor (React mode): contacts text / post moments on their own.

Mirrors proactive_monitor.ProactiveMonitor's decision logic, but runs on a plain
daemon thread (no QTimer) and does all I/O through phone_core (no Qt widget). It is
started once per chat by the init-chat hook when no Qt UI is present (see
plugin._on_init_chat). Proactive *calls* are omitted in React mode — there is no web
call UI yet — so this drives SMS + moments only.

The SMS/moment text is generated by the lightweight sms_llm (its own API, independent
of the main story loop). A proactive SMS is delivered to messages.json AND queued in
pending_proactive.json, so the next main-story turn knows the character reached out.
Scene state (who is face-to-face with the player right now) is fed in from the
message-added hook; in-scene characters are never proactively texted.
"""

from __future__ import annotations

import json
import random
import re
import threading
import time
from pathlib import Path

from sdk.logging import get_logger

logger = get_logger(__name__, plugin_id="com.shinsekai.chat_phone")


def _recent_story_context(max_lines: int = 8) -> str:
    """Digest the most recent main-story dialogue from chat_history.

    Returns a short "谁: 说了什么" transcript (player + characters + narration,
    excluding internal markers) so a proactive SMS can stay coherent with the plot.
    Empty string if no active session is found. (Copied Qt-free from
    proactive_monitor so this module never imports PySide6.)
    """
    base = Path("data/chat_history")
    if not base.is_dir():
        return ""
    try:
        dirs = sorted((d for d in base.iterdir() if d.is_dir()),
                      key=lambda p: p.stat().st_mtime, reverse=True)
    except Exception:
        return ""
    _SKIP = {"COT", "PHONE", "CALL", "CHOICE", "STAT", "bgm", "CG"}
    for d in dirs:
        aj = d / "active.json"
        if not aj.is_file():
            continue
        try:
            data = json.loads(aj.read_text(encoding="utf-8"))
        except Exception:
            continue
        msgs = data if isinstance(data, list) else data.get("messages", data.get("history", []))
        if not isinstance(msgs, list):
            return ""
        lines: list[str] = []
        for m in msgs[-14:]:
            if not isinstance(m, dict):
                continue
            role = m.get("role")
            content = m.get("content", "")
            if not isinstance(content, str):
                continue
            if role == "user":
                raw = content.strip()
                if re.match(r'^\s*\[(短信|通话|视频|视频通话)\]', raw):
                    continue
                if "请调用" in raw or "send_sms" in raw:
                    continue
                txt = re.sub(r'^\s*\[[^\]]*\]\s*', '', raw).strip()
                if txt:
                    lines.append(f"玩家: {txt[:80]}")
            elif role == "assistant":
                idx = content.find("{")
                if idx < 0:
                    continue
                try:
                    dd = json.loads(content[idx:])
                except Exception:
                    continue
                for it in dd.get("dialog", []):
                    if not isinstance(it, dict):
                        continue
                    cn = str(it.get("character_name", "") or "").strip()
                    sp = str(it.get("speech", "") or "").strip()
                    if not cn or not sp or cn in _SKIP:
                        continue
                    label = "旁白" if cn in ("NARR", "旁白") else cn
                    lines.append(f"{label}: {sp[:80]}")
        return "\n".join(lines[-max_lines:])
    return ""


def _split_moment_image(text: str) -> tuple[str, str]:
    """Split a trailing ``[图:描述]`` marker off a moment body. Returns (body, desc)."""
    m = re.search(r'[\[【]\s*图\s*[:：]\s*(.+?)\s*[\]】]\s*$', text or "")
    if m:
        return (text[:m.start()].strip(), m.group(1).strip())
    return ((text or "").strip(), "")


class ProactiveCore:
    """Qt-free periodic proactive-contact driver. See module docstring."""

    _SCENE_BACKSTOP_SEC = 7200  # 2h safety backstop (scene is a state, not a timer)
    _MOMENT_K = 0.03            # moments damping (matches ProactiveMonitor)

    def __init__(self, on_incoming_call=None) -> None:
        self._char_settings: dict[str, str] = {}
        self._freq_config: dict = {}
        self._scene_chars: dict[str, float] = {}
        self._urge: dict[str, float] = {}
        self._last_reach: dict[str, float] = {}  # last proactive SMS/call time per char (anti-spam cooldown)
        self._interval = 60.0
        self._stop = threading.Event()
        self._thread: threading.Thread | None = None
        self._lock = threading.Lock()
        self._on_incoming_call = on_incoming_call

    # ── config ────────────────────────────────────────────────────────
    def set_character_settings(self, settings: dict) -> None:
        self._char_settings = dict(settings or {})

    def set_frequency_config(self, config: dict) -> None:
        self._freq_config = dict(config or {})
        self._urge = {}
        self._last_reach = {}

    # ── scene state (fed by the message-added hook) ───────────────────
    def set_scene_character(self, name: str) -> None:
        name = (name or "").strip()
        if not name:
            return
        now = time.time()
        with self._lock:
            self._scene_chars[name] = now
            self._scene_chars = {n: ts for n, ts in self._scene_chars.items()
                                 if now - ts < self._SCENE_BACKSTOP_SEC}

    def clear_scene(self) -> None:
        with self._lock:
            self._scene_chars = {}

    def remove_scene_character(self, name: str) -> None:
        name = (name or "").strip()
        if not name:
            return
        with self._lock:
            self._scene_chars.pop(name, None)

    # ── lifecycle ─────────────────────────────────────────────────────
    def start(self, interval_sec: float = 60.0) -> None:
        if self._thread is not None and self._thread.is_alive():
            return
        self._interval = float(interval_sec)
        self._stop.clear()
        self._thread = threading.Thread(target=self._loop, daemon=True, name="proactive-core")
        self._thread.start()
        logger.info("Proactive core started (React mode, interval=%.0fs)", self._interval)

    def stop(self) -> None:
        self._stop.set()

    def _loop(self) -> None:
        # wait() returns True when stopped; the leading wait delays the first tick.
        while not self._stop.wait(self._interval):
            try:
                self._tick()
            except Exception:
                logger.debug("proactive tick failed", exc_info=True)

    def _live_prefs(self) -> tuple:
        """Re-read the on-disk knobs the bridge writes, so React 设置 changes take
        effect on the next tick with no cross-process signaling.

        Returns (enabled: bool, scale: float, dnd: bool).
        """
        from pathlib import Path
        import json as _json
        from plugins.shinsekai_chat_phone import phone_core
        enabled, scale, dnd = True, 1.0, False
        try:
            fp = Path("data/plugins/com.shinsekai.chat_phone/freq_config.json")
            if fp.exists():
                fc = _json.loads(fp.read_text(encoding="utf-8")) or {}
                enabled = bool(fc.get("_enabled", True))
                scale = float(fc.get("_scale", 1.0) or 1.0)
        except Exception:
            pass
        try:
            sp = phone_core.session_dir() / "phone_session.json"
            if sp.exists():
                sess = _json.loads(sp.read_text(encoding="utf-8")) or {}
                dnd = bool(sess.get("dnd", False))
        except Exception:
            pass
        return enabled, scale, dnd

    def _emit_call(self, name: str, video: bool) -> bool:
        """Present an incoming call through the plugin's generic host-page bridge.

        Prefers the injected on_incoming_call callback (routes to the host's
        plugin-page presentation channel, so the phone overlay pops); falls back
        to the legacy stream-sink emit for hosts without it.
        """
        event = {"type": "call.incoming", "name": name,
                 "callType": ("video" if video else "voice"),
                 "pluginId": "com.shinsekai.chat_phone", "pageId": "chat_phone_app"}
        callback = self._on_incoming_call
        if callback is not None:
            try:
                callback(event)
                return True
            except Exception:
                logger.debug("proactive call callback failed", exc_info=True)

        # Compatibility fallback for older hosts with the original call event.
        try:
            import sys
            for key in ("__main__", "main"):
                mod = sys.modules.get(key)
                getter = getattr(mod, "get_stream_sink", None) if mod is not None else None
                if getter is None:
                    continue
                sink = getter()
                if sink is not None and hasattr(sink, "emit"):
                    sink.emit(event)
                    return True
        except Exception:
            logger.debug("proactive call emit failed", exc_info=True)
        return False

    def _maybe_call(self, name: str, scale: float) -> bool:
        """Rare random incoming call from a contact (much rarer than a proactive SMS)."""
        if random.random() >= 0.01 * float(scale or 1.0):
            return False
        return self._emit_call(name, random.random() < 0.3)

    # ── the decision tick ─────────────────────────────────────────────
    def _tick(self) -> None:
        from plugins.shinsekai_chat_phone import phone_core
        enabled, scale, dnd = self._live_prefs()
        if not enabled:
            return
        fc_all = self._freq_config or {}
        contacts = phone_core.contacts_list()
        if not contacts:
            return
        try:
            from config.config_manager import ConfigManager
            valid = {c.name for c in ConfigManager().config.characters}
        except Exception:
            valid = set(contacts)
        now = time.time()
        with self._lock:
            scene = {n for n, ts in self._scene_chars.items()
                     if now - ts < self._SCENE_BACKSTOP_SEC}
        for name in contacts:
            if name not in valid:
                continue
            # 手动模式：玩家在角色设置里用拉杆指定了「每小时联系次数」(1-10)；
            # 自主模式：跟随好感度自然升温
            manual = phone_core.is_manual_freq(name)
            if manual:
                per_hour = phone_core.get_char_freq(name)
                if per_hour <= 0:
                    continue  # 玩家手动关闭了该角色的主动联系
                per_hour = max(1, min(10, int(per_hour)))
                char_scale = per_hour / 5.0  # for moments / call scaling (≈1.0 at 5/hr)
            else:
                # 自主：好感度即熟悉/亲密度，默认偏低(20)、随剧情升温，
                # 天然实现"人与人交往不是一蹴而就、刚认识不该发很多消息"
                aff = phone_core.get_affinity(name)
                if aff <= 0:
                    continue  # 好感度见底，该角色不再主动搭理玩家
                char_scale = aff / 50.0  # 20→0.4, 50→1.0, 100→2.0
                per_hour = 0
            # Moments: independent low-freq roll, unaffected by scene / no-double-text.
            if self._maybe_post_moment(name):
                continue
            if dnd:
                continue  # 勿扰: suppress proactive SMS + calls (ambient moments still allowed)
            if name in scene:
                continue  # face-to-face — say it in person, don't text / call
            try:
                from plugins.shinsekai_chat_phone.settings_app import is_character_yandere
                yandere = is_character_yandere(name)
            except Exception:
                yandere = False
            # Absolute anti-spam cooldown. Manual mode honours the exact per-hour rate the
            # player set (3600/N); auto mode scales an anti-machine-gun floor by affinity /
            # yandere. Either way, one reach-out then quiet for the cooldown window.
            if manual:
                _reach_cd = 3600.0 / per_hour
            else:
                _reach_cd = (1200.0 if yandere else 2400.0) / max(0.6, min(1.6, char_scale))
            if now - self._last_reach.get(name, 0.0) < _reach_cd:
                continue  # reached out recently — hold off this tick
            # Proactive incoming call: rare random ring (rarer than SMS), scaled by level.
            if self._maybe_call(name, scale * char_scale):
                self._last_reach[name] = now
                continue  # rang the player — don't also text this tick
            # Don't double-text: a character who already reached out and hasn't been answered
            # stays quiet (avoids "在吗?在吗?"). Yandere / 玩家手动设的高频 may follow up, but
            # all cap out at 3 unanswered in a row.
            last = phone_core.last_message(name)
            if last is not None and not last.get("is_user"):
                if not yandere and not manual:
                    continue
                streak = 0
                for _m in reversed(phone_core.messages_for(name)[-8:]):
                    if _m.get("is_user"):
                        break
                    streak += 1
                if streak >= 3:
                    continue  # already 3 unanswered in a row — back off even for yandere / manual
            # Manual fires on schedule (the player asked for this rate); auto accumulates a
            # probabilistic urge so it feels spontaneous. Both send a 1-3 line burst.
            if manual:
                self._urge[name] = 0.0
                self._send_proactive_burst(name, now)
                continue
            fc = fc_all.get(name, {}) or {}
            sms_base = fc.get("sms", 0.1) * scale * char_scale
            if yandere:
                sms_base = min(sms_base * 2.5, 0.8)
            urge = self._urge.get(name, 0.0) + random.uniform(0, sms_base * 2)
            self._urge[name] = urge
            if urge > 0.8 + random.uniform(-0.2, 0.3):
                self._urge[name] = random.uniform(0, 0.3)
                self._send_proactive_burst(name, now)

    def _send_proactive_burst(self, name: str, now: float) -> None:
        """Deliver 1-3 proactive SMS as a burst, 10-30s apart, on a side thread so the tick
        loop isn't blocked — mirrors a person firing off a couple of texts in a row rather
        than one wall-of-text. First line is immediate; each next line waits 10-30s. Each is
        generated in turn (seeing the ones already sent) so the burst stays coherent."""
        self._last_reach[name] = now  # claim the cooldown up front so the next tick won't re-fire
        count = random.randint(1, 3)

        def _run() -> None:
            from plugins.shinsekai_chat_phone import phone_core
            sent = 0
            for i in range(count):
                if self._stop.is_set():
                    break  # monitor stopped mid-burst
                text = self._generate_message(name)
                if not text:
                    continue
                try:
                    phone_core.deliver_sms_paced(name, text)   # 首条1-3s、后续+2-4s，像真人打字
                    phone_core.record_pending_proactive(name, text)
                    sent += 1
                except Exception:
                    logger.debug("proactive burst deliver failed", exc_info=True)
            if sent:
                logger.info("Proactive SMS burst (%d) from %s", sent, name)

        threading.Thread(target=_run, daemon=True, name="proactive-burst").start()

    def _generate_message(self, name: str) -> str:
        from plugins.shinsekai_chat_phone import phone_core
        setting = self._char_settings.get(name, "")
        hist: list[str] = []
        for m in phone_core.messages_for(name)[-6:]:
            who = "对方" if m.get("is_user") else name
            hist.append(f"{who}: {m.get('text', '')}")
        story = _recent_story_context()
        try:
            from plugins.shinsekai_chat_phone.sms_llm import _call_llm
            prompt = (
                "你(主动方)给对方发了一条短信，不是对方找你。"
                "结合当前剧情最近发生的事、你们之前的短信记录和你的性格，"
                "作为主动联系的一方，你会发一条什么短信？"
                "只回复短信内容，不要加任何前缀、引号或格式。"
            )
            result = _call_llm(name, setting, prompt, hist, story_context=story, initiate=True)
            if result and len(result) > 2:
                return result.strip()
        except Exception:
            logger.debug("proactive sms gen failed", exc_info=True)
        return ""

    def _maybe_post_moment(self, name: str) -> bool:
        from plugins.shinsekai_chat_phone import phone_core
        mo_base = (self._freq_config.get(name, {}) or {}).get("moments", 0.02)
        try:
            from plugins.shinsekai_chat_phone.settings_app import is_character_yandere
            if is_character_yandere(name):
                mo_base = min(mo_base * 1.6, 0.4)
        except Exception:
            pass
        if random.random() >= mo_base * self._MOMENT_K:
            return False
        text = self._generate_moment(name)
        body, desc = _split_moment_image(text)
        if not body and not desc:
            return False
        try:
            phone_core.moment_add_post(name, body, desc)
            return True
        except Exception:
            logger.debug("proactive moment failed", exc_info=True)
        return False

    def _generate_moment(self, name: str) -> str:
        setting = self._char_settings.get(name, "")
        story = _recent_story_context()
        try:
            from plugins.shinsekai_chat_phone.sms_llm import _call_llm
            prompt = (
                "你现在想发一条朋友圈动态。结合你此刻的心情、近况和当前剧情，写一两句朋友圈文案。"
                "可选：如果想配张图，就在结尾用 [图:简短画面描述] 表示（例如 [图:窗外的雨]）。"
                "只输出动态正文（含可选的 [图:...]），不要加任何前缀、引号或其它格式。"
            )
            result = _call_llm(name, setting, prompt, [], story_context=story, initiate=True)
            if result and len(result.strip()) > 1:
                return result.strip()
        except Exception:
            pass
        return ""
